export const TestNamesEnum = {
    GRE: "Graduate Record Examination",
    GMAT: "Graduate Management Admission Test",
    TOEFL: "Test of English as a Foreign Language",
    IELTS: "International English Language Testing System",
    DET: "Duolingo English Test",
    PTE: "Pearson Test of English",
    ACT: "American College Testing"
};
export const studentCounsellingStagesEnum = {
    FRESH_LEAD: "Fresh Lead",
    COUNSELLING: "Counselling",
    FOLLOW_UP_1: "Follow up 1",
    FOLLOW_UP_2: "Follow Up 2",
    FINAL_SHORTLIST: "Final Shortlist",
    CLOSED_LEAD: "Closed Lead",
    REOPENED: "Reopened"
}
export const applicationStateEnum = {
    PROCESSING: "Processing",
    ACCEPTED: "Accepted",
    REJECTED: "Rejected",
    COMPLETED: "Completed",
    CANCELLED: "Cancelled",
}
export const leadRatingEnum = {
    "high priority": "high priority",
    "medium priority": "medium priority",
    "low priority": "low priority"
};
export const leadSourceEnum = {
    None: "None",
    Advertisement: "Advertisement",
    "Bulk Leads": "Bulk Leads",
    "Channel Partner": "Channel Partner",
    "Cold Call": "Cold Call",
    "College Data": "College Data",
    "College Visit": "College Visit",
    "Digital Marketing": "Digital Marketing",
    "Direct Walkin": "Direct Walkin",
    "Edu Fair": "Edu Fair",
    Facebook: "Facebook",
    "Facebook Ads": "Facebook Ads",
    "Fair Promotion - College": "Fair Promotion - College",
    Instagram: "Instagram",
    "Instagram & FB": "Instagram & FB",
    JustDial: "JustDial",
    "Library/work-drive": "Library/work-drive",
    "Multi-Channel Campus Outreach": "Multi-Channel Campus Outreach",
    "Other Social Media": "Other Social Media",
    Others: "Others",
    "OW Number": "OW Number",
    "OW Partner College": "OW Partner College",
    "OW Summit": "OW Summit",
    "Partner Companies": "Partner Companies",
    Seminars: "Seminars",
    "Spot Evaluation Drive": "Spot Evaluation Drive",
    "Student Referral": "Student Referral",
    "Team Member Referral": "Team Member Referral",
    "Trade Show": "Trade Show",
    "Twitter (X)": "Twitter (X)",
    "UniDel Visit": "UniDel Visit",
    "Virtual Edu Fair": "Virtual Edu Fair",
    Webinar: "Webinar",
    "WebSite Visit": "WebSite Visit",
    Whatsapp: "Whatsapp",
    YouTube: "YouTube"
};

export const leadStatusEnum = {
    "New Lead": "New Lead",
    "Follow Up 1": "Follow Up 1",
    "Follow Up 2": "Follow Up 2",
    "Follow Up 3": "Follow Up 3",
    "Follow Up 4": "Follow Up 4",
    "Follow Up 5": "Follow Up 5",
    "Continuously Not Responding": "Continuously Not Responding",
    "Not Interested": "Not Interested",
    "Junk Lead": "Junk Lead",
    "Lost Lead": "Lost Lead",
    "Invalid Lead": "Invalid Lead"
};
export const applicationStagesEnum = {
    WAITING_FOR_COUNSELLOR_Approval: "Waiting For Counsellor's Approval",
    COUNSELLOR_APPROVED: "Counsellor Approved",
    COUNSELLOR_DISAPPROVED: "Counsellor Disapproved",
    REQUEST_RECEIVED: "Request Received",
    DOCUMENT_CHECKLIST: "Document checklist",
    DOCUMENTS_VERIFICATION: "Documents verification",
    APPLICATION_FORM_DRAFT: "Application form draft",
    SUBMISSION: "Submission",
    PENDING_CHECKLISTS: "Pending Checklists",
    WAITING_FOR_DECISION: "Waiting for Decision",
    RESULT_RECEIVED: "Result Received",
    FINANCIAL_DOCUMENTS: "Financial Documents",
    I20_REQUEST: "I20 Request",
    CONDITIONAL_ACCEPTANCE: "Conditional Acceptance",
    I20_RECEIVED: "I20 Received",
};
export const TestDescriptionEnum = {
    TOTAL: "Total",
    VERBAL_REASONING: "Verbal Reasoning",
    QUANTITATIVE_REASONING: "Quantitative Reasoning",
    ANALYTICAL_WRITING_ASSESSMENT: "Analytical Writing Assessment",
    READING_COMPREHENSION: "Reading Comprehension",
    LISTENING_COMPREHENSION: "Listening Comprehension",
    SPEAKING: "Speaking",
    WRITING: "Writing",
    INTEGRATED_REASONING: "Integrated Reasoning",
    QUANTITATIVE_SECTION: "Quantitative Section",
    VERBAL_SECTION: "Verbal Section",
    LISTENING: "Listening",
    READING: "Reading",
    LITERACY: "Literacy",
    CONVERSATION: "Conversation",
    COMPREHENSION: "Comprehension",
    PRODUCTION: "Production",
    ENGLISH: "English", 
    MATH: "Math", 
    SCIENCE: "Science"
};
export const TeamRoleEnum = {
    TEAM: "processCoordinator",
    DEVELOPER: "developer",
    ADMIN: "admin",
    COUNSELLOR: "counsellor",
    REMOTE_STUDENT_ADVISOR: "remoteStudentAdvisor"
};
export const UniversityTypeEnum = {
    PUBLIC: "public",
    PRIVATE: "private",
    NR: "not reported"
};
export const studyLevelEnum = {
    MS: "masters",
    BS: "bachelors"
};
export const DestinationTypeEnum = {
    USA: "United States of America",
    UK: "United Kingdom",
    CANADA: "Canada",
    AUSTRALIA: "Australia",
    IRELAND: "Ireland",
    NZ: "New Zealand"
};
export const CurrencySymbolEnum = {
    USD: "$",
    GBP: "£",
    CAD: "$",
    AUD: "AU$",
    EUR: "€",
    NZD: "$"
};
export const IndustryTypeEnum = {
    ENTERTAINMENT: "entertainment",
    FINANCE: "finance",
    MEDICAL: "medical",
    "INFORMATION TECHNOLOGY": "information technology",
    EDUCATION: "education",
    TEXTILE: "textile",
    "MEDIA AND NEWS": "media and news",
    "FOOD PROCESSING": "food processing",
    HOSPITALITY: "hospitality",
    "CONSTRUCTION AND ENGINEERING": "construction and engineering",
    LAW: "law",
    PAPER: "paper",
    "REAL ESTATE": "real estate",
    AUTOMOBILE: "automobile",
    AVIATION: "aviation",
    PHARMACEUTICAL: "pharmaceutical",
    FERTILIZERS: "fertilizers",
    ADVERTISING: "advertising",
    METALLURGY: "metallurgy",
    ENERGY: "energy",
    TELECOMMUNICATIONS: "telecommunications",
    RETAIL: "retail",
    MANUFACTURING: "manufacturing",
    AGRICULTURE: "agriculture",
    CHEMICALS: "chemicals",
    TRANSPORTATION_LOGISTICS: "transportation and logistics",
    CONSUMER_GOODS: "consumer goods",
    HEALTHCARE: "healthcare"
};
export const EducationStageEnum = {
    PRIMARY: "primary",
    SECONDARY: "secondary",
    SENIOR_SECONDARY: "senior secondary",
    UNDERGRADUATE: "undergraduate",
    GRADUATE: "graduate",
    POSTGRADUATE: "postgraduate",
    DOCTORATE: "doctorate",
};
export const WorkStyleEnum = {
    FULL_TIME: "full-time",
    PART_TIME: "part-time",
    FREELANCING: "freelancing",
    CONTRACT: "contract",
    REMOTE: "remote",
    FLEXIBLE: "flexible",
    SHIFT_WORK: "shift work",
};
export const ApplicationStatusEnum = {
    REQUEST: "Request received",
    VERIFICATION: "Document Verification",
    MASTER_APPLICATION_FORM: "Master Application Form",
    APPLICATION_UNIVERSITY_SITE: "To be Applied at University Official site"
};
export const courseTypeEnum = {
    RESEARCH: "research work",
    COURSE: "course work"
};
export const studyModeEnum = {
    ONLINE: "online",
    CAMPUS: "on-campus",
    HYBRID: "hybrid"
};
export const TernaryEnum = {
    YES: "yes",
    NO: "no",
    OPTIONAL: "optional"
};
export const possibilityOfAdmitEnum = {
    AMBITIOUS: "Ambitious",
    MODERATE: "Moderate",
    SAFE: "Safe"
}
export const disciplineEnum = {
    AGRICULTURE_FORESTRY: "Agriculture & Forestry",
    APPLIED_SCIENCES_PROFESSIONS: "Applied Sciences & Professions",
    ARTS_DESIGN_ARCHITECTURE: "Arts, Design & Architecture",
    BUSINESS_MANAGEMENT: "Business & Management",
    COMPUTER_SCIENCE_IT: "Computer Science & IT",
    EDUCATION_TRAINING: "Education & Training",
    ENGINEERING_TECHNOLOGY: "Engineering & Technology",
    ENVIRONMENTAL_STUDIES_EARTH_SCIENCES: "Environmental Studies & Earth Sciences",
    HOSPITALITY_LEISURE_SPORTS: "Hospitality, Leisure & Sports",
    HUMANITIES: "Humanities",
    JOURNALISM_MEDIA: "Journalism & Media",
    LAW: "Law",
    MEDICINE_HEALTH: "Medicine & Health",
    NATURAL_SCIENCES_MATHEMATICS: "Natural Sciences & Mathematics",
    SOCIAL_SCIENCES: "Social Sciences",
};
export const subDisciplineEnum = {
    Agriculture: "Agriculture",
    Animal_Science: "Animal Science",
    Food_Technology: "Food Technology",
    Forestry: "Forestry",
    Horticulture_and_Crop_Science: "Horticulture and Crop Science",
    Marine_Science: "Marine Science",
    Aviation_Studies: "Aviation Studies",
    Emergency_Disaster_Management: "Emergency & Disaster Management",
    Family_Consumer_Science: "Family & Consumer Science",
    Fashion_Textiles_Luxury_Goods: "Fashion, Textiles and Luxury Goods",
    Food_Science: "Food Science",
    Forensic_Science: "Forensic Science",
    Library_Science: "Library Science",
    Military_Science: "Military Science",
    Museum_Studies: "Museum Studies",
    Real_Estate_Property_Management: "Real Estate & Property Management",
    Social_Work: "Social Work",
    Architecture: "Architecture",
    Art_and_Craft: "Art and Craft",
    Art_History: "Art History",
    Ceramics_and_Sculpture: "Ceramics and Sculpture",
    Dance: "Dance",
    Design: "Design",
    Drama: "Drama",
    Fashion_Design: "Fashion Design",
    Film_Studies: "Film Studies",
    Fine_Arts: "Fine Arts",
    Graphic_Design: "Graphic Design",
    Industrial_Design: "Industrial Design",
    Interior_Design: "Interior Design",
    Landscape_Architecture: "Landscape Architecture",
    Music: "Music",
    Music_Composition: "Music Composition",
    Music_Performance: "Music Performance",
    Musicology: "Musicology",
    Painting_Drawing: "Painting & Drawing",
    Photography: "Photography",
    Urban_Planning: "Urban Planning",
    Visual_Arts: "Visual Arts",
    Accounting: "Accounting",
    Actuarial_Science: "Actuarial Science",
    Advertising: "Advertising",
    Agribusiness: "Agribusiness",
    Auditing: "Auditing",
    Banking: "Banking",
    Business_Administration: "Business Administration",
    Business_Intelligence: "Business Intelligence",
    Commerce: "Commerce",
    Construction_Management: "Construction Management",
    Corporate_Communication: "Corporate Communication",
    Corporate_Social_Responsibility: "Corporate Social Responsibility",
    Digital_Marketing: "Digital Marketing",
    Digital_Media: "Digital Media",
    Engineering_Management: "Engineering Management",
    Entrepreneurship: "Entrepreneurship",
    Executive_MBA: "Executive MBA",
    Fashion_Management: "Fashion Management",
    Finance: "Finance",
    Financial_Management: "Financial Management",
    Financial_Technology: "Financial Technology",
    Forensic_Accounting: "Forensic Accounting",
    Human_Resource_Management: "Human Resource Management",
    Innovation_Management: "Innovation Management",
    Insurance: "Insurance",
    International_Business: "International Business",
    Investment: "Investment",
    IT_Management: "IT Management",
    Leadership: "Leadership",
    Management_of_Creative_Industries: "Management of Creative Industries",
    Management_Studies: "Management Studies",
    Marketing: "Marketing",
    Marketing_Management: "Marketing Management",
    MBA: "Master in Business Administration (MBA)",
    MIM: "Master in Management (MIM)",
    Operations_Quality_Management: "Operations and Quality Management",
    Project_Management: "Project Management",
    Public_Administration: "Public Administration",
    Retail_Management: "Retail Management",
    Risk_Management: "Risk Management",
    Strategic_Management: "Strategic Management",
    Supply_Chain_Management_Logistics: "Supply Chain Management & Logistics",
    Taxation: "Taxation",
    Transport_Management: "Transport Management",
    Animation: "Animation",
    Artificial_Intelligence: "Artificial Intelligence",
    Business_Information_Systems: "Business Information Systems",
    Computer_Sciences: "Computer Sciences",
    Cyber_Security: "Cyber Security",
    Data_Analytics: "Data Analytics",
    Data_Science_Big_Data: "Data Science & Big Data",
    Game_Design: "Game Design",
    GIS: "Geographical Information Systems (GIS)",
    Health_Informatics: "Health Informatics",
    Human_Computer_Interaction: "Human Computer Interaction",
    Information_Systems: "Information Systems",
    IT: "Information Technology (IT)",
    Machine_Learning: "Machine Learning",
    Software_Engineering: "Software Engineering",
    User_Experience_Design: "User Experience Design",
    Web_Technologies_Cloud_Computing: "Web Technologies & Cloud Computing",
    Adult_Education: "Adult Education",
    Art_Education: "Art Education",
    Coaching: "Coaching",
    Early_Childhood_Education: "Early Childhood Education",
    Education: "Education",
    Educational_Leadership: "Educational Leadership",
    Educational_Psychology: "Educational Psychology",
    Educational_Research: "Educational Research",
    Health_Education: "Health Education",
    Higher_Education: "Higher Education",
    Instructional_Design: "Instructional Design",
    Literacy_Education: "Literacy Education",
    Primary_Education: "Primary Education",
    School_Counselling: "School Counselling",
    Secondary_Education: "Secondary Education",
    Special_Education: "Special Education",
    STEM_Education: "STEM Education",
    Teaching: "Teaching",
    Teaching_English_as_a_Foreign: "Teaching English as a Foreign",
    Aerospace_Engineering: "Aerospace Engineering",
    Automotive_Engineering: "Automotive Engineering",
    Bio_Biomedical_Engineering: "Bio & Biomedical Engineering",
    Chemical_Engineering: "Chemical Engineering",
    Civil_Engineering_Construction: "Civil Engineering & Construction",
    Communications_Engineering: "Communications Engineering",
    Electrical_Engineering: "Electrical Engineering",
    Electronics_Embedded_Technology: "Electronics & Embedded Technology",
    Energy_Engineering: "Energy Engineering",
    Environmental_Engineering: "Environmental Engineering",
    General_Engineering_Technology: "General Engineering & Technology",
    Industrial_Systems_Engineering: "Industrial & Systems Engineering",
    Marine_Engineering: "Marine Engineering",
    Materials_Science: "Materials Science",
    Mechanical_Engineering: "Mechanical Engineering",
    Mechatronics: "Mechatronics",
    Mining_Oil_Gas: "Mining, Oil & Gas",
    Nuclear_Engineering: "Nuclear Engineering",
    Production_Manufacturing_Engineering: "Production and Manufacturing Engineering",
    Robotics: "Robotics",
    Sound_Engineering: "Sound Engineering",
    Structural_Engineering: "Structural Engineering",
    Sustainable_Energy: "Sustainable Energy",
    Transportation_Engineering: "Transportation Engineering",
    Biodiversity_Conservation: "Biodiversity & Conservation",
    Climate_Studies_Meteorology: "Climate Studies & Meteorology",
    Earth_Sciences: "Earth Sciences",
    Ecology: "Ecology",
    Environmental_Economics_Policy: "Environmental Economics & Policy",
    Environmental_Management: "Environmental Management",
    Environmental_Sciences: "Environmental Sciences",
    Geology: "Geology",
    Hydrology_Water_Management: "Hydrology & Water Management",
    Natural_Resource_Management: "Natural Resource Management",
    Soil_Science: "Soil Science",
    Sustainable_Development: "Sustainable Development",
    Toxicology: "Toxicology",
    Culinary_Arts: "Culinary Arts",
    Event_Management: "Event Management",
    Hospitality_Management: "Hospitality Management",
    Sport_Exercise_Science: "Sport and Exercise Science",
    Sports_Management: "Sports Management",
    Tourism_Leisure: "Tourism & Leisure",
    Ancient_History: "Ancient History",
    Christian_Studies: "Christian Studies",
    Classics: "Classics",
    Creative_Writing: "Creative Writing",
    ESL: "ESL",
    Ethics: "Ethics",
    General_Studies: "General Studies",
    History: "History",
    Islamic_Studies: "Islamic Studies",
    Language_Studies: "Language Studies",
    Liberal_Arts: "Liberal Arts",
    Linguistics: "Linguistics",
    Literature: "Literature",
    Modern_History: "Modern History",
    Philosophy: "Philosophy",
    Theology_and_Religious_Studies: "Theology and Religious Studies",
    Journalism: "Journalism",
    Media_Management: "Media Management",
    Media_Studies_Mass_Media: "Media Studies & Mass Media",
    Public_Relations: "Public Relations",
    Publishing: "Publishing",
    Translation_Interpreting: "Translation & Interpreting",
    Business_Law: "Business Law",
    Civil_Private_Law: "Civil & Private Law",
    Criminal_Justice: "Criminal Justice",
    Criminal_Law: "Criminal Law",
    European_Law: "European Law",
    International_Law: "International Law",
    Legal_Studies: "Legal Studies",
    LLM: "Master of Laws (LLM)",
    Patent_Intellectual_Property_Law: "Patent & Intellectual Property Law",
    Public_Law: "Public Law",
    Biomedical_Science: "Biomedical Science",
    Clinical_Psychology: "Clinical Psychology",
    Complementary_Alternative_Medicine: "Complementary & Alternative Medicine",
    Dentistry: "Dentistry",
    Epidemiology: "Epidemiology",
    Gerontology: "Gerontology",
    Health_Administration: "Health Administration",
    Health_Sciences: "Health Sciences",
    Immunology: "Immunology",
    Kinesiology: "Kinesiology",
    Medical_Imaging: "Medical Imaging",
    Medicine: "Medicine",
    Midwifery: "Midwifery",
    Nursing: "Nursing",
    Nutrition_Dietetics: "Nutrition & Dietetics",
    Occupational_Health_and_Safety: "Occupational Health and Safety",
    Occupational_Therapy: "Occupational Therapy",
    Optometry: "Optometry",
    Pathology: "Pathology",
    Pharmacy: "Pharmacy",
    Physiology: "Physiology",
    Physiotherapy: "Physiotherapy",
    Prosthetics_and_Orthotics: "Prosthetics and Orthotics",
    Public_Health: "Public Health",
    Speech_Pathology: "Speech Pathology",
    Veterinary_Medicine: "Veterinary Medicine",
    Anatomy: "Anatomy",
    Applied_Mathematics: "Applied Mathematics",
    Astronomy_Space_Sciences: "Astronomy & Space Sciences",
    Biochemistry: "Biochemistry",
    Bioinformatics_Biostatistics: "Bioinformatics & Biostatistics",
    Biology: "Biology",
    Biotechnology: "Biotechnology",
    Botany: "Botany",
    Chemistry: "Chemistry",
    Computational_Mathematics: "Computational Mathematics",
    Financial_Mathematics: "Financial Mathematics",
    Genetics: "Genetics",
    Mathematics: "Mathematics",
    Microbiology: "Microbiology",
    Molecular_Sciences: "Molecular Sciences",
    Nanoscience_and_Nanotechnology: "Nanoscience and Nanotechnology",
    Natural_Sciences: "Natural Sciences",
    Neuroscience: "Neuroscience",
    Oceanography: "Oceanography",
    Operations_Research: "Operations Research",
    Pharmacology: "Pharmacology",
    Physics: "Physics",
    Statistics: "Statistics",
    Zoology: "Zoology",
    African_Studies: "African Studies",
    American_Australasian_Studies: "American and Australasian studies",
    Anthropology: "Anthropology",
    Archaeology: "Archaeology",
    Area_Cultural_Studies: "Area & Cultural Studies",
    Art_Therapy: "Art Therapy",
    Asian_Studies: "Asian Studies",
    Childhood_Studies: "Childhood Studies",
    Cognitive_Science: "Cognitive Science",
    Communication_Studies: "Communication Studies",
    Community_Development: "Community Development",
    Counselling_Psychology: "Counselling Psychology",
    Criminology: "Criminology",
    Developmental_Psychology: "Developmental Psychology",
    Diplomacy: "Diplomacy",
    Econometrics: "Econometrics",
    Economics: "Economics",
    Ethnic_Studies: "Ethnic Studies",
    European_Studies: "European Studies",
    Forensic_Psychology: "Forensic Psychology",
    French_Studies: "French Studies",
    Gender_Sexuality_Studies: "Gender & Sexuality Studies",
    Geography: "Geography",
    German_Scandinavian_Studies: "German and Scandinavian Studies",
    Iberian_Studies: "Iberian Studies",
    International_Development: "International Development",
    International_Relations: "International Relations",
    Italian_Studies: "Italian Studies",
    Middle_Eastern_Studies: "Middle Eastern Studies",
    Organizational_Behaviour: "Organizational Behaviour",
    Political_Science: "Political Science",
    Psychology: "Psychology",
    Public_Policy: "Public Policy",
    Slavic_Studies: "Slavic Studies",
    Social_Policy: "Social Policy",
    Social_Psychology: "Social Psychology",
    Sociology: "Sociology",
    Terrorism_Security: "Terrorism & Security",
};
export const statusEnum = {
    ONLINE: "online",
    OFFLINE: "offline"
};
export const currencySymbols = {
    "AED": "د.إ",
    "AFN": "؋",
    "ALL": "L",
    "AMD": "֏",
    "ANG": "ƒ",
    "AOA": "Kz",
    "ARS": "$",
    "AUD": "$",
    "AWG": "ƒ",
    "AZN": "₼",
    "BAM": "КМ",
    "BBD": "$",
    "BDT": "৳",
    "BGN": "лв",
    "BHD": ".د.ب",
    "BIF": "FBu",
    "BMD": "$",
    "BND": "$",
    "BOB": "Bs.",
    "BRL": "R$",
    "BSD": "$",
    "BTC": "₿",
    "BTN": "Nu.",
    "BWP": "P",
    "BYN": "Br",
    "BZD": "BZ$",
    "CAD": "$",
    "CDF": "FC",
    "CHF": "CHF",
    "CLF": "UF",
    "CLP": "$",
    "CNH": "CN¥",
    "CNY": "¥",
    "COP": "$",
    "CRC": "₡",
    "CUC": "$",
    "CUP": "$MN",
    "CVE": "$",
    "CZK": "Kč",
    "DJF": "Fdj",
    "DKK": "kr",
    "DOP": "RD$",
    "DZD": "DA",
    "EGP": "E£",
    "ERN": "Nfk",
    "ETB": "Br",
    "EUR": "€",
    "FJD": "$",
    "FKP": "£",
    "GBP": "£",
    "GEL": "₾",
    "GGP": "£",
    "GHS": "₵",
    "GIP": "£",
    "GMD": "D",
    "GNF": "FG",
    "GTQ": "Q",
    "GYD": "$",
    "HKD": "$",
    "HNL": "L",
    "HRK": "kn",
    "HTG": "G",
    "HUF": "Ft",
    "IDR": "Rp",
    "ILS": "₪",
    "IMP": "£",
    "INR": "₹",
    "IQD": "ع.د",
    "IRR": "﷼",
    "ISK": "kr",
    "JEP": "£",
    "JMD": "J$",
    "JOD": "JD",
    "JPY": "¥",
    "KES": "KSh",
    "KGS": "сом",
    "KHR": "៛",
    "KWD": "د.ك",
    "KYD": "$",
    "KZT": "₸",
    "LAK": "₭",
    "LBP": "ل.ل",
    "LKR": "රු",
    "LRD": "$",
    "LSL": "L",
    "LYD": "ل.د",
    "MAD": "د.م.",
    "MDL": "lei",
    "MGA": "Ar",
    "MKD": "ден",
    "MMK": "Ks",
    "MNT": "₮",
    "MOP": "MOP$",
    "MRU": "UM",
    "MUR": "₨",
    "MVR": "ރ.",
    "MWK": "MK",
    "MXN": "$",
    "MYR": "RM",
    "MZN": "MT",
    "NAD": "$",
    "NGN": "₦",
    "NIO": "C$",
    "NOK": "kr",
    "NPR": "₨",
    "NZD": "$",
    "OMR": "ر.ع.",
    "PAB": "B/.",
    "PEN": "S/.",
    "PGK": "K",
    "PHP": "₱",
    "PKR": "₨",
    "PLN": "zł",
    "PYG": "₲",
    "QAR": "ر.ق",
    "RON": "lei",
    "RSD": "дин.",
    "RUB": "₽",
    "RWF": "RF",
    "SAR": "ر.س",
    "SBD": "$",
    "SCR": "₨",
    "SDG": "ج.س.",
    "SEK": "kr",
    "SGD": "$",
    "SHP": "£",
    "SLL": "Le",
    "SOS": "Sh",
    "SRD": "$",
    "SSP": "£",
    "STD": "Db",
    "STN": "Db",
    "SVC": "$",
    "SYP": "£",
    "SZL": "L",
    "THB": "฿",
    "TJS": "ЅМ",
    "TMT": "T",
    "TND": "د.ت",
    "TOP": "T$",
    "TRY": "₺",
    "TTD": "TT$",
    "TWD": "NT$",
    "TZS": "TSh",
    "UAH": "₴",
    "UGX": "USh",
    "USD": "$",
    "UYU": "$U",
    "UZS": "лв",
    "VES": "Bs.",
    "VND": "₫",
    "VUV": "VT",
    "WST": "T",
    "XAF": "FCFA",
    "XAG": "XAG",
    "XAU": "XAU",
    "XCD": "$",
    "XDR": "SDR",
    "XOF": "CFA",
    "XPD": "XPD",
    "XPF": "CFP",
    "XPT": "XPT",
    "YER": "﷼",
    "ZAR": "R",
    "ZMW": "ZK",
    "ZWL": "$"
}
export const keywords = [
    {
        type: "disciplines",
        strings: [
            "Agriculture & Forestry",
            "Applied Sciences & Professions",
            "Arts, Design & Architecture",
            "Business & Management",
            "Computer Science & IT",
            "Education & Training",
            "Engineering & Technology",
            "Environmental Studies & Earth Sciences",
            "Hospitality, Leisure & Sports",
            "Humanities",
            "Journalism & Media",
            "Law",
            "Medicine & Health",
            "Natural Sciences & Mathematics",
            "Social Sciences",
        ]
    },
    {
        type: "subDisciplines",
        strings: [
            'Agriculture',
            'Animal Science',
            'Food Technology',
            'Forestry',
            'Horticulture and Crop Science',
            'Marine Science',
            'Aviation Studies',
            'Emergency & Disaster Management',
            'Family & Consumer Science',
            'Fashion, Textiles and Luxury Goods',
            'Food Science',
            'Forensic Science',
            'Library Science',
            'Military Science',
            'Museum Studies',
            'Real Estate & Property Management',
            'Social Work',
            'Architecture',
            'Art and Craft',
            'Art History',
            'Ceramics and Sculpture',
            'Dance',
            'Design',
            'Drama',
            'Fashion Design',
            'Film Studies',
            'Fine Arts',
            'Graphic Design',
            'Industrial Design',
            'Interior Design',
            'Landscape Architecture',
            'Music',
            'Music Composition',
            'Music Performance',
            'Musicology',
            'Painting & Drawing',
            'Photography',
            'Urban Planning',
            'Visual Arts',
            'Accounting',
            'Actuarial Science',
            'Advertising',
            'Agribusiness',
            'Auditing',
            'Banking',
            'Business Administration',
            'Business Intelligence',
            'Commerce',
            'Construction Management',
            'Corporate Communication',
            'Corporate Social Responsibility',
            'Digital Marketing',
            'Digital Media',
            'Engineering Management',
            'Entrepreneurship',
            'Executive MBA',
            'Fashion Management',
            'Finance',
            'Financial Management',
            'Financial Technology',
            'Forensic Accounting',
            'Human Resource Management',
            'Innovation Management',
            'Insurance',
            'International Business',
            'Investment',
            'IT Management',
            'Leadership',
            'Management of Creative Industries',
            'Management Studies',
            'Marketing',
            'Marketing Management',
            'Master in Business Administration (MBA)',
            'Master in Management (MIM)',
            'Operations and Quality Management',
            'Project Management',
            'Public Administration',
            'Retail Management',
            'Risk Management',
            'Strategic Management',
            'Supply Chain Management & Logistics',
            'Taxation',
            'Transport Management',
            'Animation',
            'Artificial Intelligence',
            'Business Information Systems',
            'Computer Sciences',
            'Cyber Security',
            'Data Analytics',
            'Data Science & Big Data',
            'Game Design',
            'Geographical Information Systems (GIS)',
            'Health Informatics',
            'Human Computer Interaction',
            'Information Systems',
            'Information Technology (IT)',
            'Machine Learning',
            'Software Engineering',
            'User Experience Design',
            'Web Technologies & Cloud',
            'Adult Education',
            'Art Education',
            'Coaching',
            'Early Childhood Education',
            'Education',
            'Educational Leadership',
            'Educational Psychology',
            'Educational Research',
            'Health Education',
            'Higher Education',
            'Instructional Design',
            'Literacy Education',
            'Primary Education',
            'School Counselling',
            'Secondary Education',
            'Special Education',
            'STEM Education',
            'Teaching',
            'Teaching English as a Foreign Language',
            'Aerospace Engineering',
            'Automotive Engineering',
            'Bio & Biomedical Engineering',
            'Chemical Engineering',
            'Civil Engineering & Construction',
            'Communications Engineering',
            'Electrical Engineering',
            'Electronics & Embedded Technology',
            'Energy Engineering',
            'Environmental Engineering',
            'General Engineering & Technology',
            'Industrial & Systems Engineering',
            'Marine Engineering',
            'Materials Science',
            'Mechanical Engineering',
            'Mechatronics',
            'Mining, Oil & Gas',
            'Nuclear Engineering',
            'Production and Manufacturing Engineering',
            'Robotics',
            'Sound Engineering',
            'Structural Engineering',
            'Sustainable Energy',
            'Transportation Engineering',
            'Biodiversity & Conservation',
            'Climate Studies & Meteorology',
            'Earth Sciences',
            'Ecology',
            'Environmental Economics & Policy',
            'Environmental Management',
            'Environmental Sciences',
            'Geology',
            'Hydrology & Water Management',
            'Natural Resource Management',
            'Soil Science',
            'Sustainable Development',
            'Toxicology',
            'Culinary Arts',
            'Event Management',
            'Hospitality Management',
            'Sport and Exercise Science',
            'Sports Management',
            'Tourism & Leisure',
            'Ancient History',
            'Christian Studies',
            'Classics',
            'Creative Writing',
            'ESL',
            'Ethics',
            'General Studies',
            'History',
            'Islamic Studies',
            'Language Studies',
            'Liberal Arts',
            'Linguistics',
            'Literature',
            'Modern History',
            'Philosophy',
            'Theology and Religious Studies',
            'Journalism',
            'Media Management',
            'Media Studies & Mass Media',
            'Public Relations',
            'Publishing',
            'Translation & Interpreting',
            'Business Law',
            'Civil & Private Law',
            'Criminal Justice',
            'Criminal Law',
            'European Law',
            'International Law',
            'Legal Studies',
            'Master of Laws (LLM)',
            'Patent & Intellectual Property Law',
            'Public Law',
            'Biomedical Science',
            'Clinical Psychology',
            'Complementary & Alternative Medicine',
            'Dentistry',
            'Epidemiology',
            'Gerontology',
            'Health Administration',
            'Health Sciences',
            'Immunology',
            'Kinesiology',
            'Medical Imaging',
            'Medicine',
            'Midwifery',
            'Nursing',
            'Nutrition & Dietetics',
            'Occupational Health and Safety',
            'Occupational Therapy',
            'Optometry',
            'Pathology',
            'Pharmacy',
            'Physiology',
            'Physiotherapy',
            'Prosthetics and Orthotics',
            'Public Health',
            'Speech Pathology',
            'Veterinary Medicine',
            'Anatomy',
            'Applied Mathematics',
            'Astronomy & Space Sciences',
            'Biochemistry',
            'Bioinformatics & Biostatistics',
            'Biology',
            'Biotechnology',
            'Botany',
            'Chemistry',
            'Computational Mathematics',
            'Financial Mathematics',
            'Genetics',
            'Mathematics',
            'Microbiology',
            'Molecular Sciences',
            'Nanoscience and Nanotechnology',
            'Natural Sciences',
            'Neuroscience',
            'Oceanography',
            'Operations Research',
            'Pharmacology',
            'Physics',
            'Statistics',
            'Zoology',
            'African Studies',
            'American and Australasian studies',
            'Anthropology',
            'Archaeology',
            'Area & Cultural Studies',
            'Art Therapy',
            'Asian Studies',
            'Childhood Studies',
            'Cognitive Science',
            'Communication Studies',
            'Community Development',
            'Counselling Psychology',
            'Criminology',
            'Developmental Psychology',
            'Diplomacy',
            'Econometrics',
            'Economics',
            'Ethnic Studies',
            'European Studies',
            'Forensic Psychology',
            'French Studies',
            'Gender & Sexuality Studies',
            'Geography',
            'German and Scandinavian Studies',
            'Iberian Studies',
            'International Development',
            'International Relations',
            'Italian Studies',
            'Middle Eastern Studies',
            'Organisational Behaviour',
            'Political Science',
            'Psychology',
            'Public Policy',
            'Slavic Studies',
            'Social Policy',
            'Social Psychology',
            'Sociology',
            'Terrorism & Security',
        ]
    },

]