export const destinationList = {
    "United States of America": {
        Arizona: [
            "Flagstaff",
            "Tucson",
            "Tempe",
            "Phoenix",
            "Tempe Junction",
            "Mesa",
            "Peoria",
            "Glendale",
            "Florence",
            "Prescott",
        ],
        Ohio: [
            "Cincinnati",
            "Dayton",
            "Oxford",
            "Cleveland",
            "Columbus",
            "Kent",
            "Athens",
            "Youngstown",
            "Bowling Green",
            "Ada",
            "Tiffin",
            "Yellow Springs",
            "Ashland",
            "Findlay",
            "University Heights",
            "Springfield",
            "Berea",
            "North Canton",
            "Portsmouth",
            "Akron",
            "Westerville",
            "Steubenville",
            "Rootstown",
            "Cedarville",
            "Hiram",
            "Toledo",
            "Marietta",
            "Rio Grande",
            "Bluffton",
            "Logan",
            "Cleveland Heights",
            "Oregon",
            "Riverside",
            "Reading",
            "Dublin",
            "Oberlin",
        ],
        "South Carolina": [
            "Columbia",
            "Clemson",
            "Orangeburg",
            "Charleston",
            "Conway",
            "Greenville",
            "Rock Hill",
            "Greenwood",
            "Spartanburg",
            "Anderson",
            "Aiken",
            "Florence",
            "Clinton",
            "Central",
        ],
        Massachusetts: [
            "Cambridge",
            "Worcester",
            "Boston",
            "Medford",
            "North Dartmouth",
            "Amherst",
            "Lowell",
            "North Andover",
            "Springfield",
            "Bridgewater",
            "Westfield",
            "Chestnut Hill",
            "Buzzards Bay",
            "Framingham",
            "Waltham",
            "Northampton",
            "Salem",
            "Longmeadow",
            "Beverly",
            "Williamstown",
            "Fitchburg",
            "Wenham",
            "Weston",
            "North Adams",
            "Newton",
            "South Hadley",
            "Haverhill",
            "Chicopee",
            "Dudley",
            "Babson Park",
            "Brookline",
            "Milton",
            "Amherst Center",
            "East Longmeadow",
            "Andover",
            "Adams",
            "Barnstable",
            "Easthampton",
        ],
        "New York": [
            "Troy",
            "Ithaca",
            "Brooklyn",
            "Syracuse",
            "Rochester",
            "New York City",
            "Valhalla",
            "Albany",
            "Old Westbury",
            "Stony Brook",
            "Alfred",
            "Riverdale",
            "Potsdam",
            "Hempstead",
            "New Paltz",
            "Throggs Neck",
            "The Bronx",
            "Queens",
            "Sparkill",
            "Garden City",
            "Keuka Park",
            "Bronxville",
            "Annandale-on-Hudson",
            "Oswego",
            "Elmira",
            "Purchase",
            "Cortland",
            "Buffalo",
            "Brookville",
            "Newburgh",
            "Poughkeepsie",
            "Utica",
            "Hamilton",
            "Vestal",
            "Loudonville",
            "Geneseo",
            "Canton",
            "Brockport",
            "Saratoga Springs",
            "Niagara University",
            "Dobbs Ferry",
            "Oneonta",
            "Staten Island",
            "Plattsburgh",
            "Fredonia",
            "Manhattan",
            "Binghamton",
            "Monroe",
            "Hornell",
            "Pleasantville",
            "Harrison",
            "Sleepy Hollow",
        ],
        California: [
            "San Diego",
            "Long Beach",
            "Santa Clara",
            "Stanford",
            "Los Angeles",
            "Davis",
            "San Francisco",
            "Claremont",
            "Irvine",
            "Santa Cruz",
            "Berkeley",
            "Riverside",
            "Northridge",
            "Merced",
            "Fresno",
            "Sacramento",
            "Fullerton",
            "Santa Barbara",
            "Rohnert Park",
            "Stockton",
            "Carson",
            "Monterey",
            "Pasadena",
            "Hayward",
            "Seaside",
            "Turlock",
            "La Verne",
            "La Jolla",
            "Orange",
            "Loma Linda",
            "San Bernardino",
            "San Rafael",
            "San Marcos",
            "Arcata",
            "Azusa",
            "Bakersfield",
            "Malibu",
            "Chico",
            "Burbank",
            "Moraga",
            "Redlands",
            "Aliso Viejo",
            "Camarillo",
            "Thousand Oaks",
            "La Mirada",
            "Santa Clarita",
            "San Jose",
            "Atherton",
            "Rosemead",
            "Costa Mesa",
            "Redding",
            "San Luis Obispo",
            "Valencia",
            "Pomona",
            "Beverly Hills",
            "Malibu Beach",
            "Home Gardens",
            "Oakland",
            "Poway",
            "Pittsburg",
        ],
        Indiana: [
            "Notre Dame",
            "Indianapolis",
            "West Lafayette",
            "Terre Haute",
            "Gary",
            "Fort Wayne",
            "Hammond",
            "New Albany",
            "Valparaíso",
            "Evansville",
            "Bloomington",
            "South Bend",
            "Muncie",
            "Goshen",
            "Marion",
            "Richmond",
            "Upland",
            "Anderson",
            "Winona Lake",
            "Kokomo",
            "North Manchester",
            "Valparaiso",
            "Michigan City",
            "Washington",
        ],
        Kansas: [
            "Lawrence",
            "Wichita",
            "Manhattan",
            "Pittsburg",
            "Topeka",
            "Emporia",
            "Hays",
            "Baldwin City",
            "Leavenworth",
            "Kansas City",
            "Newton",
            "Arkansas City",
        ],
        Illinois: [
            "Chicago",
            "Normal",
            "Champaign",
            "Evanston",
            "DeKalb",
            "Peoria",
            "Romeoville",
            "Charleston",
            "Carbondale",
            "Macomb",
            "Springfield",
            "Joliet",
            "Lebanon",
            "Lisle",
            "Rockford",
            "Lake Forest",
            "Naperville",
            "Edwardsville",
            "River Forest",
            "Wheaton",
            "Deerfield",
            "Aurora",
            "Decatur",
            "North Chicago",
            "Rock Island",
            "Urbana",
            "Wheeling",
            "Oswego",
            "Moline",
            "Greenville",
        ],
        Texas: [
            "College Station",
            "Houston",
            "Arlington",
            "Victoria",
            "Denton",
            "Stephenville",
            "Lubbock",
            "San Marcos",
            "San Antonio",
            "Dallas",
            "Prairie View",
            "Beaumont",
            "Kingsville",
            "Tyler",
            "Longview",
            "Fort Worth",
            "Canyon",
            "Corpus Christi",
            "Galveston",
            "Waco",
            "Nacogdoches",
            "Huntsville",
            "San Angelo",
            "Abilene",
            "Irving",
            "Keene",
            "Laredo",
            "Austin",
            "Belton",
            "Wichita Falls",
            "Texarkana",
            "Edinburg",
            "Odessa",
            "Richardson",
            "El Paso",
            "Marshall",
            "Texas City",
            "Webster",
            "Helotes",
            "Commerce",
            "Decatur",
            "Missouri City",
        ],
        "District of Columbia": ["Washington", "Fort Lesley J McNair"],
        Michigan: [
            "Detroit",
            "Kalamazoo",
            "Ann Arbor",
            "Dearborn",
            "Southfield",
            "East Lansing",
            "Houghton",
            "Ypsilanti",
            "Rochester Hills",
            "University Center",
            "Big Rapids",
            "Mount Pleasant",
            "Allendale",
            "Flint",
            "Livonia",
            "Berrien Springs",
            "Marquette",
            "Grand Rapids",
            "Troy",
            "Midland",
            "Fair Plain",
            "Highland Park",
        ],
        Florida: [
            "Orlando",
            "Gainesville",
            "Daytona Beach",
            "Melbourne",
            "Coral Gables",
            "Tallahassee",
            "Boca Raton",
            "Miami",
            "Tampa",
            "Jacksonville",
            "Fort Lauderdale",
            "DeLand",
            "Pensacola",
            "Babson Park",
            "Fort Myers",
            "Lakeland",
            "West Palm Beach",
            "St. Augustine",
            "Saint Leo",
            "Winter Park",
            "Hialeah",
            "Springfield",
            "Florida City",
            "Jacksonville Beach",
            "Davie",
            "North Miami",
            "Memphis",
            "Sarasota",
            "Fort Myers Beach",
        ],
        Missouri: [
            "St. Louis",
            "Rolla",
            "Kansas City",
            "St. Charles",
            "Cape Girardeau",
            "Springfield",
            "Warrensburg",
            "Maryville",
            "Parkville",
            "Kirksville",
            "Marshall",
            "Columbia",
            "St. Joseph",
            "Chesterfield",
            "Saint Louis",
            "Pacific",
            "Webster Groves",
            "Saint Charles",
            "Washington",
            "Jefferson City",
        ],
        "New Jersey": [
            "Hoboken",
            "Princeton",
            "Glassboro",
            "Newark",
            "Teaneck",
            "Montclair",
            "Galloway",
            "West Long Branch",
            "Union",
            "South Orange",
            "Mahwah",
            "Lawrenceville",
            "Ewing",
            "Madison",
            "Morristown",
            "New Brunswick",
            "Jersey City",
            "Wayne",
            "Ocean Acres",
            "Elizabeth",
            "Camden",
            "Passaic",
            "Ramsey",
        ],
        Colorado: [
            "Boulder",
            "Fort Collins",
            "Denver",
            "Golden",
            "Pueblo",
            "Grand Junction",
            "Gunnison",
            "Greeley",
            "Durango",
            "Lakewood",
            "Colorado Springs",
            "Frederick",
        ],
        "New Mexico": ["Las Cruces", "Socorro", "Las Vegas", "Albuquerque"],
        "North Carolina": [
            "Raleigh",
            "Greenville",
            "Winston-Salem",
            "Greensboro",
            "High Point",
            "Durham",
            "Charlotte",
            "Chapel Hill",
            "Boone",
            "Elon",
            "Wilmington",
            "Fayetteville",
            "Misenheimer",
            "Cullowhee",
            "Buies Creek",
            "Pembroke",
            "Mars Hill",
            "Laurinburg",
            "Wingate",
            "Montreat",
            "Nashville",
            "Carolina Beach",
            "Albemarle",
            "Asheville",
            "Lumberton",
        ],
        Oklahoma: [
            "Stillwater",
            "Edmond",
            "Weatherford",
            "Oklahoma City",
            "Tahlequah",
            "Norman",
            "Langston",
            "Lawton",
            "Tulsa",
            "Bethany",
            "Claremore",
        ],
        Alabama: [
            "Auburn",
            "Huntsville",
            "Tuscaloosa",
            "Mobile",
            "Tuskegee",
            "Jacksonville",
            "Florence",
            "Birmingham",
            "Montgomery",
            "Troy",
            "Montevallo",
            "Livingston",
            "Oxford",
            "Madison",
            "Russellville",
            "Oneonta",
        ],
        Minnesota: [
            "Mankato",
            "Saint Paul",
            "Moorhead",
            "Minneapolis",
            "Winona",
            "Marshall",
            "Bemidji",
            "St. Cloud",
            "Saint Cloud",
            "Duluth",
            "Fairfax",
            "Rochester",
            "Plymouth",
        ],
        Mississippi: [
            "Mississippi State",
            "University",
            "Hattiesburg",
            "Jackson",
            "Clinton",
            "Cleveland",
            "Columbus",
            "Lorman",
            "Starkville",
            "West Hattiesburg",
            "Philadelphia",
            "Winona",
            "Columbia",
            "Meridian",
        ],
        Pennsylvania: [
            "Pittsburgh",
            "University Park",
            "Philadelphia",
            "Bethlehem",
            "Erie",
            "Wilkes-Barre",
            "Villanova",
            "Lewisburg",
            "Millersville",
            "Chester",
            "Latrobe",
            "Shippensburg",
            "Indiana",
            "Scranton",
            "Reading",
            "Bryn Mawr",
            "Allentown",
            "Glenside",
            "Bloomsburg",
            "St. Davids",
            "Elizabethtown",
            "Kutztown",
            "Rosemont",
            "Lincoln University",
            "Mechanicsburg",
            "Beaver Falls",
            "East Stroudsburg",
            "Moon Township",
            "Greensburg",
            "Elkins Park",
            "Clarks Summit",
            "Langhorne",
            "Harrisburg",
            "West Chester",
            "Selinsgrove",
            "Loretto",
            "California",
            "Slippery Rock",
            "Annville",
            "Lock Haven",
            "York",
            "Williamsport",
            "Edinboro",
            "Clarion",
            "Middletown",
            "Ardmore",
            "Grove City",
            "Hershey",
            "Huntingdon",
            "Montgomeryville",
            "New Castle",
            "Carlisle",
            "Paoli",
        ],
        "West Virginia": [
            "Morgantown",
            "Huntington",
            "Institute",
            "Fairmont",
            "West Liberty",
            "Shepherdstown",
            "Philippi",
            "Athens",
            "Bethany",
            "Charleston",
        ],
        Georgia: [
            "Atlanta",
            "Athens",
            "Macon",
            "Kennesaw",
            "Statesboro",
            "Savannah",
            "Columbus",
            "Carrollton",
            "Valdosta",
            "Dahlonega",
            "Augusta",
            "Lookout Mountain",
            "Decatur",
            "Morrow",
            "Milledgeville",
            "Gainesville",
            "Doraville",
            "Lawrenceville",
            "Marietta",
            "Martinez",
        ],
        Tennessee: [
            "Chattanooga",
            "Knoxville",
            "Nashville",
            "Harrogate",
            "Memphis",
            "Cookeville",
            "Murfreesboro",
            "Johnson City",
            "Cleveland",
            "Lebanon",
            "Jefferson City",
            "Jackson",
            "Tullahoma",
            "Springfield",
            "Lakeland",
        ],
        "North Dakota": ["Grand Forks", "Fargo", "Minot"],
        Kentucky: [
            "Lexington",
            "Louisville",
            "Morehead",
            "Bowling Green",
            "Murray",
            "Richmond",
            "Highland Heights",
            "Frankfort",
            "Midway",
            "Lexington-Fayette",
        ],
        Virginia: [
            "Norfolk",
            "Fairfax",
            "Richmond",
            "Charlottesville",
            "Lynchburg",
            "Virginia Beach",
            "Williamsburg",
            "Radford",
            "Petersburg",
            "Arlington",
            "Farmville",
            "Harrisonburg",
            "Newport News",
            "Roanoke",
            "Hampton",
            "Winchester",
            "Bridgewater",
            "Blacksburg",
            "Fredericksburg",
            "Manassas",
        ],
        Connecticut: [
            "West Haven",
            "Fairfield",
            "New Haven",
            "New Britain",
            "Bridgeport",
            "Storrs",
            "West Hartford",
            "Hamden",
            "Danbury",
            "Middletown",
            "Cromwell",
            "Hartford",
        ],
        Nevada: ["Reno", "Las Vegas", "Winchester"],
        "New Hampshire": [
            "Hanover",
            "Durham",
            "Plymouth",
            "Henniker",
            "Manchester",
            "Keene",
            "Weare",
        ],
        Utah: [
            "Logan",
            "Provo",
            "Ogden",
            "Cedar City",
            "Orem",
            "St. George",
            "Salt Lake City",
            "Saint George",
        ],
        Maryland: [
            "College Park",
            "Baltimore",
            "Towson",
            "Princess Anne",
            "Frostburg",
            "Westminster",
            "Frederick",
            "Salisbury",
            "Takoma Park",
            "California",
            "Baltimore Highlands",
            "Langley Park",
            "Maryland City",
            "Chevy Chase",
        ],
        Wisconsin: [
            "Madison",
            "Milwaukee",
            "River Falls",
            "Menomonie",
            "La Crosse",
            "Oshkosh",
            "Green Bay",
            "Whitewater",
            "Stevens Point",
            "Mequon",
            "Eau Claire",
            "Waukesha",
            "Kenosha",
            "Ashland",
            "Evansville",
            "Menominee",
            "Somers",
        ],
        Nebraska: [
            "Omaha",
            "Lincoln",
            "Bellevue",
            "Chadron",
            "Crete",
            "Wayne",
            "Hastings",
            "Kearney",
            "Fremont",
            "Nebraska City",
        ],
        Louisiana: [
            "Baton Rouge",
            "New Orleans",
            "Lafayette",
            "Lake Charles",
            "Ruston",
            "Thibodaux",
            "Monroe",
            "Hammond",
            "Shreveport",
            "Abbeville",
        ],
        Oregon: [
            "Corvallis",
            "Portland",
            "Klamath Falls",
            "Eugene",
            "Salem",
            "Newberg",
            "Ashland",
            "Monmouth",
            "La Grande",
            "Forest Grove",
            "Dallas",
        ],
        Montana: ["Bozeman", "Missoula", "Billings", "Butte"],
        Washington: [
            "Seattle",
            "Pullman",
            "Lacey",
            "Bellingham",
            "Ellensburg",
            "Spokane",
            "Tacoma",
            "Kirkland",
            "Cheney",
            "Olympia",
            "Kenmore",
        ],
        "South Dakota": [
            "Vermillion",
            "Rapid City",
            "Brookings",
            "Aberdeen",
            "Spearfish",
            "Sioux Falls",
            "Madison",
        ],
        Arkansas: [
            "Fayetteville",
            "Jonesboro",
            "Russellville",
            "Little Rock",
            "Pine Bluff",
            "Magnolia",
            "Conway",
            "Siloam Springs",
            "Searcy",
            "Arkadelphia",
        ],
        Iowa: [
            "Ames",
            "Des Moines",
            "Cedar Falls",
            "Fairfield",
            "Dubuque",
            "Iowa City",
            "Davenport",
            "Sioux Center",
        ],
        Delaware: ["Newark", "Dover", "New Castle", "Wilmington"],
        "Rhode Island": [
            "Providence",
            "Kingston",
            "Bristol",
            "Newport",
            "Smithfield",
            "East Greenwich",
            "North Smithfield",
            "North Providence",
        ],
        Hawaii: ["Honolulu", "Hilo"],
        Idaho: ["Moscow", "Pocatello", "Boise", "Nampa", "Idaho Falls"],
        Wyoming: ["Laramie"],
        Alaska: ["Fairbanks", "Anchorage", "Juneau"],
        Maine: ["Orono", "Bangor", "Portland", "Biddeford", "Gorham"],
        Vermont: ["Plainfield", "Colchester", "Burlington"],
        "Washington, D.C.": ["Washington, D. C."],
    },
    Australia: {
        "New South Wales": [
            "Sydney",
            "Penrith",
            "Wollongong",
            "Bathurst",
            "Lismore",
            "North Sydney",
            "Armidale",
            "Callaghan",
            "Paramatta",
            "Camperdown",
            "Paddington, Sydney, NSW",
            "Newcastle",
            "Kensington",
            "Albury",
            "Lugarno",
        ],
        "Western Australia": [
            "Crawley",
            "Perth",
            "Murdoch",
            "Joondalup",
            "Fremantle",
        ],
        Victoria: [
            "Clayton",
            "Melbourne",
            "Geelong",
            "Ballarat",
            "Hawthorn",
            "Caulfield North",
            "Bendigo",
        ],
        "South Australia": ["Adelaide"],
        Queensland: [
            "Toowoomba",
            "Gold Coast",
            "Brisbane",
            "Sippy Downs",
            "Townsville",
            "St Lucia",
            "Buderim",
            "Cairns",
            "Bilinga",
            "Gatton",
            "Springfield Central",
        ],
        "Australian Capital Territory": ["Canberra"],
        "Northern Territory": ["Darwin"],
        Tasmania: ["Hobart", "Launceston"],
    },
    Canada: {
        "British Columbia": [
            "Burnaby",
            "Victoria",
            "Prince George",
            "Nanaimo",
            "Abbotsford",
            "Vancouver",
            "Langley",
            "Kamloops",
        ],
        Ontario: [
            "Toronto",
            "Ottawa",
            "Hamilton",
            "Waterloo",
            "Windsor",
            "Kingston",
            "Sudbury",
            "Thunder Bay",
            "St. Catharines",
            "Oshawa",
            "Peterborough",
            "Guelph",
            "North Bay",
            "London",
        ],
        Alberta: ["Edmonton", "Calgary", "Lethbridge"],
        "Nova Scotia": ["Halifax", "Wolfville"],
        Saskatchewan: ["Saskatoon", "Regina"],
        Quebec: ["Montréal", "Sherbrooke", "Quebec City"],
        Manitoba: ["Winnipeg", "Brandon"],
        "New Brunswick": ["Fredericton"],
        "Newfoundland and Labrador": ["St John’s"],
        "Prince Edward Island": ["Charlottetown"],
        other: [
            "Winnipeg",
            "Saskatoon",
            "Lethbridge",
            "Ottawa",
            "Victoria",
            "Greater Sudbury",
            "Thunder Bay",
            "Terrace",
            "Montréal",
            "London",
            "Fredericton",
            "Halifax",
            "Edmonton",
            "Toronto",
            "Guelph",
            "Vancouver",
            "St. John's",
            "Burnaby",
            "Kingston",
            "Hamilton",
            "Regina",
            "Calgary",
            "Nanaimo",
            "Waterloo",
            "Oshawa",
            "St. Catharines",
            "Brantford",
            "Mississauga",
            "Windsor",
            "City of Langley",
            "Kelowna",
            "Sydney",
            "Brandon",
            "Charlottetown",
            "Antigonish",
            "Sackville",
            "Prince George",
            "Saint John",
            "North Bay",
            "Sherbrooke",
        ],
    },
    "New Zealand": {
        Waikato: ["Hamilton"],
        Auckland: ["Auckland"],
        "Manawatu-Wanganui": ["Palmerston North"],
        Wellington: ["Wellington"],
        Canterbury: ["Christchurch", "Lincoln"],
        Otago: ["Dunedin"],
        other: [
            "Wellington",
            "Dunedin",
            "Christchurch",
            "Hamilton",
            "Auckland",
            "Palmerston North",
            "North Shore",
        ],
    },
    Ireland: {
        "County Galway": ["Galway"],
        "County Limerick": ["Limerick"],
        "County Dublin": ["Dublin", "Dún Laoghaire"],
        "County Cork": ["Cork", "Bishopstown"],
        "County Kildare": ["Maynooth"],
        "County Louth": ["Dundalk"],
        "County Carlow": ["Carlow"],
        other: [
            "Limerick",
            "Maynooth",
            "Dublin",
            "Cork",
            "Waterford",
            "Galway",
            "Sligo",
            "Dún Laoghaire",
        ],
        "N Ireland": ["Dublin"],
    },
    "United Kingdom": {
        "Yorkshire and the Humber": [
            "Sheffield",
            "Leeds",
            "Huddersfield",
            "Bradford",
            "Hull",
            "York",
        ],
        "East of England": [
            "Cranfield",
            "Hatfield",
            "Luton",
            "Cambridge",
            "Lincoln",
            "Colchester",
            "Norwich",
            "Chelmsford",
            "Ipswich",
        ],
        Wales: [
            "Pontypridd",
            "Swansea",
            "Aberystwyth",
            "Cardiff",
            "Carmarthen",
            "Bangor",
            "Newport",
            "Wrexham",
            "Lampeter",
        ],
        "North West England": [
            "Salford",
            "Bolton",
            "Liverpool",
            "Manchester",
            "Lancaster",
            "Carlisle",
            "Chester",
            "Ormskirk",
            "Preston",
        ],
        London: [
            "London",
            "Kingston upon Thames",
            "Uxbridge",
            "Ealing",
            "Twickenham",
        ],
        Scotland: [
            "Glasgow",
            "Aberdeen",
            "Dundee",
            "Edinburgh",
            "St Andrews",
            "Stirling",
            "Inverness",
            "Kirkwall",
            "Musselburgh",
            "Oban",
            "Ayr",
            "Perth",
        ],
        "East Midlands": [
            "Nottingham",
            "Leicester",
            "Loughborough",
            "Derby",
            "Northampton",
        ],
        "South West England": [
            "Bristol",
            "Bath",
            "Cheltenham",
            "Plymouth",
            "Poole",
            "Falmouth",
            "Gloucester",
            "Exeter",
            "Cirencester",
        ],
        "West Midlands": [
            "Birmingham",
            "Coventry",
            "Stoke-on-Trent",
            "Keele",
            "Wolverhampton",
            "Worcester",
        ],
        "South East England": [
            "Southampton",
            "Guildford",
            "Brighton",
            "Oxford",
            "Canterbury",
            "Portsmouth",
            "Egham",
            "Reading",
            "Buckingham",
            "Farnham",
            "Chichester",
            "Winchester",
        ],
        "North East England": [
            "Newcastle upon Tyne",
            "Middlesbrough",
            "Durham",
            "Sunderland",
        ],
        "Northern Ireland": ["Coleraine", "Belfast"],
        England: [
            "Cambridge",
            "Canterbury",
            "Colchester",
            "Manchester",
            "London",
            "Liverpool",
            "Birmingham",
            "Newcastle upon Tyne",
            "Nottingham",
            "Oxford",
            "Norwich",
            "Keele",
            "Brighton",
            "Durham",
            "Sheffield",
            "Southampton",
            "Bradford",
            "Hertford",
            "Chester",
            "Bristol",
            "Exeter",
            "York",
            "Cranfield",
            "Bournemouth",
            "Cirencester",
            "Reading",
            "Lancaster",
            "Lincoln",
            "Loughborough",
            "Winchester",
            "Middlesbrough",
            "Leeds",
            "Coventry",
            "Salford",
            "Guildford",
            "Derby",
            "Hatfield",
            "Preston",
            "Huddersfield",
            "Sunderland",
            "Ipswich",
            "Bath",
            "Luton",
            "Worcester",
            "Cheltenham",
            "Hull",
            "Falmouth",
            "Abbey Wood",
            "Plymouth",
            "Portsmouth",
            "Wolverhampton",
            "Chatham",
            "Leicester",
            "Northampton",
            "Gloucester",
            "Bolton",
            "Grantham",
            "City of London",
            "Carlisle",
            "Stoke-on-Trent",
            "Buckingham",
            "Walsall",
            "Penryn",
            "Chichester",
            "Buxton",
            "Bedford",
            "Chelmsford",
            "Shrewsbury",
            "Newport",
            "Lambeth",
            "Swindon",
        ],
        "N Ireland": ["Belfast", "Coleraine"],
    },
};